name: Workflow dispatch test

on:
  workflow_dispatch:
    inputs:
      count:
        description: 'Test count'
        required: false
        default: NULL

jobs:
  testCount:
    runs-on: ubuntu-latest
    steps:
    - run: |
        export COUNT = 2
        case $COUNT in
          ''|*[!0-9]*) echo info: COUNT: $COUNT is NULL, continuing with count calculations; \
                       echo counting... ;;
          *) echo COUNT: $COUNT ;;
        esac
#        if [ -z "${{ github.event.inputs.count }}" ]; then
#          echo "info: ${{ github.event.inputs.count }} is NULL, continuing with count calculations"
#        else
#          echo "info: ${{ github.event.inputs.count }} is NOT NULL"
#          if [[ ${{ github.event.inputs.count }} =~ ^[0-9]+$ ]]; then
#            echo "info: ${{ github.event.inputs.count }} is a number"
#          else
#            echo "error: ${{ github.event.inputs.count }} is NOT a number"
#            exit 1
#          fi
#        fi
