name: Workflow dispatch test

on:
  workflow_dispatch:
    inputs:
      count:
        description: 'Test count'
        required: false
        default: NULL

jobs:
  testCount:
    runs-on: ubuntu-latest
    steps:
    - run: |
        if [ -z "${{ github.event.inputs.count }}" ]
        then
          echo "${{ github.event.inputs.count }} is NULL"
        else
          echo "${{ github.event.inputs.count }} is NOT NULL"
        fi

