name: Workflow dispatch test

on:
  workflow_dispatch:
    inputs:
      count:
        description: 'Test count'
        required: false
        default: ""

jobs:
  testCount:
    runs-on: ubuntu-latest
    steps:
    - name: case
      run: |
        case "${{ github.event.inputs.count }}" in
          *[0-9]*) echo "info: COUNT: ${{ github.event.inputs.count }}"; \
                   echo "CALC=$(echo ${{ github.event.inputs.count }} - 2 | bc)" \>\> $GITHUB_ENV ;;
          "") echo "info COUNT is empty: ${{ github.event.inputs.count }}" ;;
          *) echo "info: COUNT is not a number: ${{ github.event.inputs.count }}"; \
             exit 1 ;;
        esac

    - name: case and env var test
      run: |
        echo "CALC = $CALC"
