name: Workflow dispatch test

on:
  workflow_dispatch:
    inputs:
      count:
        description: 'Test count'
        required: false
        default: ""

jobs:
  testCount:
    runs-on: ubuntu-latest
    steps:
    - name: case
      run: |
        case "${{ inputs.count }}" in
          *[0-9]) echo "info: COUNT: ${{ inputs.count }}"; \
                  echo "A=aaa" >> $GITHUB_ENV; \
                  echo "CALC=$(echo ${{ inputs.count }} - 2 | bc --standard)" >> $GITHUB_ENV; \
                  echo "B=bbb" >> $GITHUB_ENV; \
                  echo "C=ccc" >> $GITHUB_ENV ;;
          "") echo "info COUNT is empty: ${{ inputs.count }}" ;;
          *) echo "info: COUNT is not a number: ${{ inputs.count }}"; \
             exit 1 ;;
        esac

    - name: case and env var test
      run: |
        echo "CALC = $CALC"
        echo "A = $A"
        echo "B = $B"
        echo "C = $C"
